#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

export DECODER="${DECODER:-detail_residual}"
export LOSS_MODE="${LOSS_MODE:-rf_ssim_wlmse_gabor}"
export LATENT_DIM="${LATENT_DIM:-384}"
export TEMPORAL_CHANNELS="${TEMPORAL_CHANNELS:-128}"
export BASE_CHANNELS="${BASE_CHANNELS:-96}"
export DROPOUT="${DROPOUT:-0.25}"
export WEIGHT_DECAY="${WEIGHT_DECAY:-1e-3}"
export LR="${LR:-3e-4}"
export GABOR_LOSS_WEIGHT="${GABOR_LOSS_WEIGHT:-0.02}"
export BASE_FRAME_PRIOR_WEIGHT="${BASE_FRAME_PRIOR_WEIGHT:-0.35}"
export LOW_AUX_SIGMA="${LOW_AUX_SIGMA:-2.0}"
export LOW_AUX_WEIGHT="${LOW_AUX_WEIGHT:-0.12}"
export LOW_AUX_SSIM_WEIGHT="${LOW_AUX_SSIM_WEIGHT:-0.02}"
export EDGE_LOSS_WEIGHT="${EDGE_LOSS_WEIGHT:-0.08}"
export LAPLACIAN_LOSS_WEIGHT="${LAPLACIAN_LOSS_WEIGHT:-0.05}"
export HIGHFREQ_LOSS_WEIGHT="${HIGHFREQ_LOSS_WEIGHT:-0.08}"
export HIGHFREQ_SIGMA="${HIGHFREQ_SIGMA:-2.0}"
export RESIDUAL_GATE="${RESIDUAL_GATE:-rf_scalar}"
export RESIDUAL_WEIGHT="${RESIDUAL_WEIGHT:-0.15}"
export GATE_L1_WEIGHT="${GATE_L1_WEIGHT:-0.01}"
export CONSISTENCY_WEIGHT="${CONSISTENCY_WEIGHT:-0.02}"
export SINGLE_REPEAT_LOSS_WEIGHT="${SINGLE_REPEAT_LOSS_WEIGHT:-0.02}"
export RUN_NAME="${RUN_NAME:-rgc_detailres_lag${RESPONSE_LAG:-3}_h${HISTORY_BINS:-11}_seed${SEED:-1}}"

bash run_rgc_frame_decoder.sh
